### PR TITLE
Add support for excluding globs instead of only filenames

### PR DESCRIPTION
**Pull request by ohcibi**

### CODE REVIEW

**Comment by rickharrison** [comment]
Can you please rebase this into one commit.

**Comment by ohcibi** [comment]
Done

**Comment by rickharrison** [comment]
Sorry, but I actually had to revert this change, because it was a breaking change and I didn't realize it. I added a new test. Could you try to get your PR working with this new test?

**Comment by ohcibi** [comment]
I'll have a look, but one question: the test says "it accepts a string" but you are passing an array? What is this test actually about? 8-)

**Comment by rickharrison** [comment]
Sorry, the current format of exclude is an array of strings

**Comment by ohcibi** [comment]
@rickharrison  The test reads like a simple string is also supported (instead of the whole array, e.g. if only one exclude is needed), though. I could PR this as well, if you like 8-)

**Comment by rickharrison** [comment]
sure go for it.

**Comment by rickharrison** [comment]
If you just mean renaming the test that is. We don't need to support a simple string. An array of strings is fine.

**Comment by ohcibi** [comment]
done

**Pull request merged**
