### PR TITLE
Match extensions at path end.

### PR DESCRIPTION
**Pull request by nathanhammond**
The current implementation matches mid-path "extensions." Hoping that you can release a new version after this lands. :)

### CODE REVIEW

**Comment by rickharrison** [comment]
Thanks for submitting this. Could you elaborate a little bit more for me on the bug it is fixing?

**Comment by nathanhammond** [comment]
I'm creating a proposal for changing the default pattern ember-cli uses when building applications to support interesting new things like ServiceWorkers, HTTP2, and SPDY.

As a result I need to have each asset included individually. That works unless for some reason the path name masquerades as an extension, in which case you get this error:

```
Build failed.
File: bower_components/loader.js/loader.js
ENOENT: no such file or directory, open '/tmp/fingerprint-output_path-oa046dKV.tmp/bower_components/loader-698e28810a2748f3c53f0a26af030729.js/loader.js'
```

**Comment by rickharrison** [comment]
Cool, thanks for the explanation!

**Comment by rickharrison** [comment]
Published as `2.4.1`

**Pull request merged**
