### PR TITLE
Add failing test for font-face

### PR DESCRIPTION
**Pull request by cibernox**
To help to trace down #42

### CODE REVIEW

**Comment by cibernox** [comment]
@rickharrison Have you had a chance to run this tests and see the failure? Just to confirm that is a legitimate bug and not that I'm doing something wrong.

**Comment by rickharrison** [comment]
So for me this test is passing. the only change I had to make was to remove the #robotoregular from the outputted css. I think you might have an issue in your broccoli definition. Could you post how you are trying to use broccoli asset rev and your folder structure?

**Comment by rickharrison** [comment]
I'm going to close this for now. Please let me know if you figured out your issue or not.

**Comment by cibernox** [comment]
I forgot about this. I figured it out. If I recall correctly the problem was that I was prepending the url with a `/`, but I'm not 100% sure I'm telling you the truth.

Thanks!

**Comment by rickharrison** [comment]
Cool, glad its all worked out!

**Pull request closed without merging**
