### PR TITLE
options.exportAssetMap writes assets/assetMap-HASH.js

### PR DESCRIPTION
**Pull request by pwfisher**
and adds assetMap.js to asset map, for asset rewrite
usage: `<script src="assets/assetMap.js">` in html source

This allows client side JS to use versioned assets via `window.ASSET_MAP`.

### CODE REVIEW

**Comment by briangonzalez** [comment]
:+1:

**Comment by rickharrison** [comment]
I think this should be in its own module. You can use the `generateAssetMap` option and then consume it however you would like. I can link to your module from the README.

**Comment by pwfisher** [comment]
This option is comparable to `generateRailsManifest` in that it produces a version of the asset manifest which is useful in certain environments. What is different about this feature that makes you want to keep it separate?

**Comment by rickharrison** [comment]
Because rails is a defined spec that a lot of people use. This is something that is specific to your build process.

To be honest, I am going to refactor this soon to reduce the amount of options being passed into the module. I will most likely land on just having one export option, which can then be transformed as needed to how you need it in your build.

**Comment by rickharrison** [comment]
I'm going to close this for now. Do you think you could try and see if you can use `generateAssetMap` and consume that somehow since it is just json?

**Pull request closed without merging**
