### PR TITLE
Make broccoli-asset-rev run before ember-asset-loader

### PR DESCRIPTION
**Pull request by Cryrivers**
`ember-asset-loader` generates asset lists by walking through the post-process tree, which needs `broccoli-asset-rev` to run before `ember-asset-loader` to make sure all files have been fingerprinted in production build before the asset list compilation.

### CODE REVIEW

**Comment by rickharrison** [comment]
@nathanhammond Would you mind weighing in here? I am not fully up to speed on all the ember addon stuff.

**Comment by Cryrivers** [comment]
@rickharrison I already pinged @nathanhammond and @trentmwillis on slack

**Comment by trentmwillis** [comment]
I think this will only work for simple use cases. I think broccoli-asset-rev should actually run _after_ ember-asset-loader, _but_ it needs to run replacements on the `asset-manifest.json` file that gets generated. If we have this run before, then `ember-asset-loader` won't include any potential `prepend` information.

The reason this works for simpler cases is because broccoli-asset-rev renames the output files, thus when ember-asset-loader generates a manifest by walking the directories, the files have been properly renamed. When using `prepend`, however, that information isn't part of the file name.

**Comment by Cryrivers** [comment]
@trentmwillis yes, I totally agree with you. @rickharrison can we add `json` to `replaceExtensions`?

**Comment by nathanhammond** [comment]
The `.json` can be specified by the user of the addon, doesn't need to be a default.

**Comment by nathanhammond** [comment]
See also: https://github.com/rickharrison/broccoli-asset-rev/issues/111

**Comment by Cryrivers** [comment]
@nathanhammond @trentmwillis I think I'm closing this PR in favor of manifest prefixing.

Thank you guys.

**Pull request closed without merging**
