### PR TITLE
Allow manifest.json to be generated without fingerprint

### PR DESCRIPTION
**Pull request by elucid**
if added to exclude list

### CODE REVIEW

**Comment by elucid** [comment]
See #38 for discussion.

**Comment by rickharrison** [comment]
Could you please add a test for this?

**Comment by elucid** [comment]
I tried adding a test but ran into difficulties because the manifest includes mtime for fingerprinted assets. Consequently the content and fingerprinted filename are different each test run.

If you have a suggestion as to how I can work around this please let me know.

**Comment by rickharrison** [comment]
Hmm, maybe you can just check the filepath and not assert that its contents are the same?

**Comment by elucid** [comment]
Added a test that only asserts the correct paths exist.

While all tests pass on my machine, the Travis build is failing. Not sure if it's legit (failing with `Could not find .travis.yml, using standard configuration.`).

**Comment by rickharrison** [comment]
Apologies about the delay. Could you rebase and then I will merge?

**Comment by elucid** [comment]
No worries. Rebased.

**Comment by rickharrison** [comment]
Thanks!

**Pull request merged**
